language: rust
sudo: false

env:
  global:
    - secure: GG/Noox5eHyfLxzdo8q/B4I+JbFabIajJlqaQP70cH1IBUxFpiXTjhIea7bzPFCDf8oARnrrjh0h3N7Gi0mNPMLoYTfN8nY0aYtkkPY6yY4kot0h0iih+cmwv0AXvT30qcgR0d+A4K1Vq+HjBOSbY+jCYH1YjdKBDxR3YlaQhFs=
script:
  - cargo build --verbose
  - cargo doc --verbose
  - ./check-line-length.sh

after_success:
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && bash upload-docs.sh'

branches:
  only: master

notifications:
  email:
    on_success: never
